codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: 50%
        threshold: 5%
    patch:
      default:
        target: 60%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "vendor/**/*"
  - "**/*_test.go"
  - "**/testdata/**"
